version: '3'

services:
  mysql:
    image: mysql:5.7.29
    container_name: mysql_homo
    restart: unless-stopped
    ports:
      - "9306:3306"
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_USER: laravel_db
      MYSQL_PASSWORD: 123456789
      MYSQL_ROOT_PASSWORD: 123456789
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql

  php:
    build:
      context: .
      dockerfile: Dockerfile
      ports:
        - "7000:80"
